-- Database roles and grants for the "app" schema. Generated by `make roles`.
-- Apply as a role holding CREATEROLE, once, before the first `make migrate`.
-- Safe to re-apply. Set the password for the application role out of band.

-- app_owner: owns the schema, applies the DDL, serves nothing.
DO $app$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_owner') THEN
    CREATE ROLE app_owner NOLOGIN;
  END IF;
END
$app$;

-- app_app: what the application connects as. DML only, subject to every policy.
DO $app$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_app') THEN
    CREATE ROLE app_app LOGIN;
  END IF;
END
$app$;

-- The schema, owned so that the default privileges below actually bind.
CREATE SCHEMA IF NOT EXISTS "app" AUTHORIZATION app_owner;
GRANT USAGE ON SCHEMA "app" TO app_app;

-- Existing objects, for a schema that was migrated before these roles existed.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "app" TO app_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "app" TO app_app;

-- Everything app_owner creates from here on. Without this, the table added by the
-- next migration is invisible to the application until somebody re-runs the GRANT.
ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA "app"
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_app;
ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA "app"
  GRANT USAGE, SELECT ON SEQUENCES TO app_app;

-- The ledger is revoked at the end of every migration rather than here, because
-- it does not exist until the first one has run. See app/store/migrate.py.
